/**
 * Bullet model - Experience Bank (Read-only, pipeline artifacts)
 * Bullets are individual experience points generated by the pipeline.
 */
export interface Bullet {
  id: string;
  bullet_id: string;
  story_id: string;
  job_id?: string;
  text: string;
  skills: string[];
  metrics?: string;
  evidence_strength: EvidenceStrength;
  risk_flags: string[];
  ordinal: number;
  created_at: string;
  updated_at: string;
}

export type EvidenceStrength = 'high' | 'medium' | 'low';
