import { Bullet } from './bullet.model';

/**
 * Story model - Experience Bank (Read-only, pipeline artifacts)
 * Stories are generated by the resume pipeline and represent
 * grouped experiences with associated bullets.
 */
export interface Story {
  id: string;
  story_id: string;
  user_id: string;
  job_id: string;
  title?: string;
  description?: string;
  bullets: Bullet[];
  created_at: string;
  updated_at: string;
}
